# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				bat = true
				glow_squid = true
				tropical_fish = true
				skeleton = true
				trader_llama = true
				zombie = true
				frog = true
				wandering_trader = true
				item_frame = true
				creeper = true
				slime = true
				item = true
				enderman = true
				zombie_villager = true
				spider = true
				skeleton_horse = true
				turtle = true
				squid = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.creeperoverhaul]
				cave_creeper = true
				swamp_creeper = true

